### ISSUE TITLE
Extract cardano-tx-submit-webapi to own git repo

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer#254]
As an independent service it would be best developed in it's own git repository

**Comment by erikd** [comment]
If this repo was already large I could see the point of this, but its not a large repo and currently contains three components.

In addition, due to the way we handle IOHK developed components, splitting this into is own repo would double the maintenance burden with respect to keeping it in this repo.

**Comment by erikd** [comment]
I should also note that I initially thought this should be in a separate repo, but @dcoutts thought it would be better here. I now agree with Duncan.
