### ISSUE TITLE
Move and Rename the cardano-explorer-node and cardano-explorer-db into a new repository

### ISSUE THREAD

**Issue by vhulchenko-iohk** [input-output-hk/cardano-explorer#276]

**Comment by erikd** [comment]
The current description of this ticket does not make sense because at least one of the remaining components relies on `cardano-explorer-db`.

Also rather than moving things from one repo to a new one we should investigate whether renaming is not a better option. @KtorZ @rhyslbw

**Comment by rhyslbw** [comment]
The main steps are to:
- Create new repo `cardano-db-sync`
- Copy service `cardano-explorer-node` into the new repo, renamed as `cardano-db-sync`
- Copy service `cardano-extended-db-node` into the new repo, renamed as `cardano-db-sync-extended`
- Copy lib `cardano-explorer-db` into the new repo, renamed as `cardano-db` (or this could be `cardano-db-model` for more specificity)
- Copy the supporting config and documentation that is directly required by the application.
- Refactor `Explorer` references to be aligned with the new scoping of this service simply synchronising the chain into the DB. I can assist with this and updating documentation to reflect the code changes

From here the SR team can migrate the nix ops code.

**Comment by dcoutts** [comment]
@rhyslbw are you sure you don't want the `cardano-db-sync-extended` to live with the explorer backend, afterall this is exclusively for the use of the explorer's DB. It's probably a better pattern to establish, to have customised `cardano-db-sync-*` components live with the projects that needed them.

**Comment by rhyslbw** [comment]
It's actually a dependency for Cardano GraphQL, which is to be a primary API service within the Adrestia suite (rather than it being a specific "explorer backend"). Keeping this alongside `cardano-db-sync` allows a reference of the plugin idea to be maintained, but I can see it both ways. It's a question of ownership. Does the node team wish to maintain this extended version? If not, then we should bring it over into `cardano-graphql`

**Comment by rhyslbw** [comment]
Just ran this by @erikd and we're both in favour of keeping them together for practicality of maintenance, and to ensure the extended version is given the same visibility for others to use. This is the reason it's named _extended_ rather than referencing the specific use-case for Cardano GraphQL. We can reconcile the ownership issue by saying that `input-output-hk/cardano-db-sync` is a collaboration between the core team and the Adrestia team, which as a side-effect, also serves as an e2e demonstration of the custom behaviour injection

**Comment by erikd** [comment]
This has been merged to master at input-output-hk/cardano-db-sync .

Any further issues should be logged there.
